spring.application.name=gamefy_back
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/gamefy
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect