spring.application.name=gamefy_back
server.port=8080
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://localhost:5432/gamefy
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration (Placeholder - Update with real SMTP details)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medoussemaboussida@gmail.com
spring.mail.password=sutmlighcpwvgpyl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Auth Configuration
google.client.id=930889646068-pj188o9hflisqg9tbe8bt9pm710cql5i.apps.googleusercontent.com